// Generated by tool/generate_web_brand_assets.py. Edit branding/feixe.json.
import 'dart:ui';

const feixeViewBox = 64.0;
const feixeBeamOrigin = Offset(54, 35);
const feixePlanes = <({double opacity, List<Offset> points})>[
  (
    opacity: 1.0,
    points: [
      Offset(12, 13),
      Offset(54, 6),
      Offset(54, 18),
      Offset(24, 23),
      Offset(24, 58),
      Offset(12, 58)
    ]
  ),
  (
    opacity: 1.0,
    points: [Offset(31, 32), Offset(54, 28), Offset(54, 42), Offset(31, 38)]
  ),
  (
    opacity: 0.32,
    points: [Offset(24, 25), Offset(31, 32), Offset(31, 38), Offset(24, 43)]
  ),
];
