[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library@^1.12.4
    prenticedavid/MCUFRIEND_kbv@^3.0.0
    https://github.com/ricmoo/QRCode.git
