from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class ExplanationSourceOut(BaseModel):
    title: str
    url: str

    model_config = {"from_attributes": True}


class ThesisExplanationOut(BaseModel):
    paragraphs: list[str]
    sources: list[ExplanationSourceOut]

    model_config = {"from_attributes": True}


class ThesisOut(BaseModel):
    id: int
    text: str
    theme_id: int
    theme_name: str
    coverage: float = Field(description="% candidatos com posição definida")
    explanation: ThesisExplanationOut | None = None

    model_config = {"from_attributes": True}


class QuestionsResponse(BaseModel):
    theses: list[ThesisOut]
    total: int


class AnswerIn(BaseModel):
    thesis_id: int
    answer: str = Field(pattern="^(agree|disagree|neutral|skip)$")
    weight: int = Field(default=1, ge=1, le=2)


class SubmitQuizIn(BaseModel):
    device_id: UUID | None = Field(
        default=None,
        description="Anonymous UUID v4 generated by the client device.",
    )
    candidate_ids: list[int] | None = Field(
        default=None,
        min_length=1,
        max_length=50,
        description="Candidaturas escolhidas pela pessoa para compor o ranking.",
    )
    answers: list[AnswerIn] = Field(min_length=1, max_length=60)

    @field_validator("device_id")
    @classmethod
    def validate_device_id_is_uuidv4(cls, value: UUID | None) -> UUID | None:
        if value is not None and value.version != 4:
            raise ValueError("device_id must be a UUID v4")
        return value

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "device_id": "550e8400-e29b-41d4-a716-446655440000",
                    "answers": [
                        {"thesis_id": 1, "answer": "agree", "weight": 2},
                        {"thesis_id": 2, "answer": "disagree", "weight": 1},
                        {"thesis_id": 3, "answer": "neutral", "weight": 1},
                    ]
                }
            ]
        }
    }


class ThesisMatchOut(BaseModel):
    thesis_id: int
    thesis_text: str
    theme_id: int
    user_answer: str
    candidate_position: str
    candidate_analysis: str | None
    match_type: str


class CandidateResultOut(BaseModel):
    candidate_id: int
    name: str
    party_acronym: str
    party_logo_url: str | None
    photo_url: str | None
    score_percent: float
    score_by_theme: dict[str, float]
    rank: int = Field(description="Colocação no ranking beta; 0 quando inelegível")
    counted_theses: int = Field(ge=0, description="Teses efetivamente comparadas com o plano")
    answered_theses: int = Field(ge=0, description="Respostas do usuário, sem as puladas")
    comparable_categories: int = Field(
        ge=0, description="Categorias presentes nas comparações efetivas"
    )
    documented_theses: int = Field(
        ge=0, description="Posições categóricas comparáveis no plano para toda a edição"
    )
    documented_categories: int = Field(
        ge=0, description="Categorias com posição comparável no plano em toda a edição"
    )
    ranking_status: str = Field(
        pattern="^(eligible|insufficient_documented_coverage|insufficient_answer_coverage)$"
    )
    ranking_eligible: bool
    matches: list[ThesisMatchOut]


class SubmitQuizResponse(BaseModel):
    results: list[CandidateResultOut]
