#!/usr/bin/env python3
"""Export the approved Feixe vector to Flutter, SVG, web, Android and iOS.

Run from any directory: python3 mobile/tool/generate_web_brand_assets.py
Requires Pillow. The canonical geometry lives in branding/feixe.json.
Fonts are the vendored Inter files, licensed in test/fixtures/fonts/OFL.txt.
No AI-rendered text or external font download is used by this exporter.
"""

import json
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
ICONS = WEB / "icons"
BRAND = ROOT / "branding"
GEOMETRY = json.loads((BRAND / "feixe.json").read_text())
FONTS = ROOT / "test/fixtures/fonts"
BACKGROUND = "#131313"


def _draw_mark(image: Image.Image, left: float, top: float, size: float) -> None:
    scale = size / GEOMETRY["viewBox"]
    for plane in GEOMETRY["planes"]:
        layer = Image.new("RGBA", image.size)
        points = [(left + x * scale, top + y * scale) for x, y in plane["points"]]
        ImageDraw.Draw(layer).polygon(
            points, fill=(255, 255, 255, round(255 * plane["opacity"]))
        )
        image.alpha_composite(layer)


def _icon(size: int, *, safe: bool) -> Image.Image:
    canvas = size * 4
    image = Image.new("RGBA", (canvas, canvas), BACKGROUND)
    padding = canvas * (0.15 if safe else 0.025)
    _draw_mark(image, padding, padding, canvas - padding * 2)
    return image.convert("RGB").resize((size, size), Image.Resampling.LANCZOS)


def _social_preview() -> Image.Image:
    scale = 2
    image = Image.new("RGBA", (1200 * scale, 630 * scale), BACKGROUND)

    # Static institutional composition. Only result cards randomize direction.
    mark_x, mark_y, mark_size = 800, 164, 340
    origin_x, origin_y = GEOMETRY["beamOrigin"]
    origin = (mark_x + origin_x / 64 * mark_size,
              mark_y + origin_y / 64 * mark_size)
    layer = Image.new("RGBA", image.size)
    beam = [(0, -25), (750, -240), (750, 170), (0, 25)]
    angle = math.radians(-8)
    points = [((origin[0] + x * math.cos(angle) - y * math.sin(angle)) * scale,
               (origin[1] + x * math.sin(angle) + y * math.cos(angle)) * scale)
              for x, y in beam]
    ImageDraw.Draw(layer).polygon(points, fill=(255, 255, 255, 22))
    image.alpha_composite(layer)
    _draw_mark(image, mark_x * scale, mark_y * scale, mark_size * scale)
    _draw_mark(image, 56 * scale, 42 * scale, 64 * scale)

    draw = ImageDraw.Draw(image)

    def text(x: int, y: int, value: str, size: int, weight: str, color: str) -> None:
        font = ImageFont.truetype(str(FONTS / f"Inter-{weight}.ttf"), size * scale)
        draw.text((x * scale, y * scale), value, font=font, fill=color, anchor="lt")

    text(136, 60, "farol político", 34, "ExtraBold", "#FFFFFF")
    text(64, 205, "Com quais propostas", 62, "ExtraBold", "#FFFFFF")
    text(64, 280, "você se identifica?", 62, "ExtraBold", "#FFFFFF")
    text(66, 390, "Descubra sua afinidade com as propostas", 27, "Regular", "#E2E2E2")
    text(66, 429, "para a Presidência de 2026.", 27, "Regular", "#E2E2E2")
    text(66, 555, "fpolitico.com.br", 25, "SemiBold", "#BDBDBD")
    return image.convert("RGB").resize((1200, 630), Image.Resampling.LANCZOS)


def _svg(*, favicon: bool) -> str:
    background = '<rect width="64" height="64" rx="12" fill="#131313"/>' if favicon else ""
    paths = []
    for plane in GEOMETRY["planes"]:
        points = " ".join(f"{x},{y}" for x, y in plane["points"])
        paths.append(f'  <polygon points="{points}" fill="#fff" fill-opacity="{plane["opacity"]}"/>')
    return '\n'.join([
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-labelledby="title">',
        '  <title id="title">Farol Político — Feixe</title>',
        *([f'  {background}'] if background else []),
        *paths,
        '</svg>\n',
    ])


def _dart_geometry() -> str:
    planes = []
    for plane in GEOMETRY["planes"]:
        points = ', '.join(f'Offset({x}, {y})' for x, y in plane["points"])
        planes.append(f'  (opacity: {plane["opacity"]}, points: [{points}]),')
    x, y = GEOMETRY["beamOrigin"]
    return '\n'.join([
        '// Generated by tool/generate_web_brand_assets.py. Edit branding/feixe.json.',
        "import 'dart:ui';",
        '',
        f'const feixeViewBox = {GEOMETRY["viewBox"]}.0;',
        f'const feixeBeamOrigin = Offset({x}, {y});',
        'const feixePlanes = <({double opacity, List<Offset> points})>[',
        *planes,
        '];\n',
    ])


def main() -> None:
    ICONS.mkdir(parents=True, exist_ok=True)
    dart_path = ROOT / 'lib/core/branding/feixe_geometry.dart'
    dart_path.parent.mkdir(parents=True, exist_ok=True)
    dart_path.write_text(_dart_geometry())
    (BRAND / 'feixe.svg').write_text(_svg(favicon=False))
    (WEB / 'favicon.svg').write_text(_svg(favicon=True))

    exports = [
        (WEB / 'favicon.png', 64, False),
        (ICONS / 'apple-touch-icon.png', 180, False),
        (ICONS / 'Icon-192.png', 192, False),
        (ICONS / 'Icon-512.png', 512, False),
        (ICONS / 'Icon-maskable-192.png', 192, True),
        (ICONS / 'Icon-maskable-512.png', 512, True),
    ]
    android = ROOT / 'android/app/src/main/res'
    for density, size in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)]:
        exports.append((android / f'mipmap-{density}/ic_launcher.png', size, False))
    ios = ROOT / 'ios/Runner/Assets.xcassets/AppIcon.appiconset'
    catalog = json.loads((ios / 'Contents.json').read_text())
    for item in catalog['images']:
        size = round(float(item['size'].split('x')[0]) * float(item['scale'].rstrip('x')))
        exports.append((ios / item['filename'], size, False))
    for path, size, safe in exports:
        _icon(size, safe=safe).save(path, optimize=True)
    _social_preview().save(WEB / 'og-preview.png', optimize=True)
    print(f'Feixe: {len(set(path for path, _, _ in exports))} PNG icons, social preview, SVGs and Dart geometry exported.')


if __name__ == '__main__':
    main()
