"""initial_schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-04-23 19:17:00.220059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_devices_last_seen', ['last_seen_at'], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acronym', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('spectrum', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('number')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_slug', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index('ix_themes_area', ['area'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('legal_name', sa.String(length=256), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('coalition', sa.String(length=512), nullable=True),
    sa.Column('ballot_number', sa.Integer(), nullable=True),
    sa.Column('running_mate', sa.String(length=256), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('office', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('election_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'office', 'election_year', 'election_round', name='uq_candidates_external_office_year_round')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_office_year_state', ['office', 'election_year', 'state'], unique=False)
        batch_op.create_index('ix_candidates_party_id', ['party_id'], unique=False)

    op.create_table('theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.create_index('ix_theses_theme_status_year', ['theme_id', 'status', 'election_year'], unique=False)

    op.create_table('candidate_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'thesis_id', name='uq_positions_candidate_thesis')
    )
    with op.batch_alter_table('candidate_positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_thesis', ['thesis_id'], unique=False)

    op.create_table('government_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'thesis_id', 'election_year', name='uq_responses_device_thesis_year')
    )
    with op.batch_alter_table('quiz_responses', schema=None) as batch_op:
        batch_op.create_index('ix_responses_device_year', ['device_id', 'election_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_responses_device_year')

    op.drop_table('quiz_responses')
    op.drop_table('government_plans')
    with op.batch_alter_table('candidate_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_thesis')

    op.drop_table('candidate_positions')
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.drop_index('ix_theses_theme_status_year')

    op.drop_table('theses')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_party_id')
        batch_op.drop_index('ix_candidates_office_year_state')

    op.drop_table('candidates')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index('ix_themes_area')

    op.drop_table('themes')
    op.drop_table('parties')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_last_seen')

    op.drop_table('devices')
    # ### end Alembic commands ###
